apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: retail-store-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: public.ecr.aws/aws-containers/retail-store-sample-orders:0.4.0
        env:
        - name: DB_USER
          value: "orders_user"
        - name: DB_PASSWORD
          value: "default_password"
        - name: DB_NAME
          value: "orders"
        - name: DB_ENDPOINT
          value: "mysql.retail-store-sample.svc.cluster.local"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 45
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: retail-store-sample
spec:
  selector:
    app: orders
  ports:
  - port: 80
    targetPort: 8080
