apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: retail-store-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: public.ecr.aws/aws-containers/retail-store-sample-ui:0.4.0
        env:
        - name: ENDPOINTS_CATALOG
          value: "http://catalog.retail-store-sample.svc.cluster.local"
        - name: ENDPOINTS_CARTS
          value: "http://carts.retail-store-sample.svc.cluster.local"
        - name: ENDPOINTS_ORDERS
          value: "http://orders.retail-store-sample.svc.cluster.local"
        - name: ENDPOINTS_CHECKOUT
          value: "http://checkout.retail-store-sample.svc.cluster.local"
        - name: ENDPOINTS_ASSETS
          value: "http://assets.retail-store-sample.svc.cluster.local"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: retail-store-sample
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
  - port: 80
    targetPort: 8080
